export const MENU_PERMISSION_MAP: Record<string, string> = {

  // ✅ Yeh 7 DB permissions ke against map hain
  'Brand'           : 'Brand',
  'HotelConfigration': 'HotelConfigration',
  'Market '         : 'HotelConfigration',
  'Outlet'          : 'Outlet',
  'OutletMenu'      : 'HotelConfigration',
  'OutletDesignation': 'HotelConfigration',
  'OutletUser'      : 'OutletUser',
  'OutletPaymentMode': 'HotelConfigration',
  'OrderTypeConfiguration': 'HotelConfigration',
  'Warehouse'       : 'HotelConfigration',
  'Masters'         : 'HotelConfigration',
  'country '        : 'HotelConfigration',
  'states'          : 'HotelConfigration',
  'city'            : 'HotelConfigration',
  'HotelTypeMasters': 'HotelConfigration',
  'UserType'        : 'HotelConfigration',
  'TableManagement' : 'TableManagement',
  'TableDepartment' : 'HotelConfigration',
  'TableManagementPage': 'TableManagementPage',
  'TaxProuductGroup': 'HotelConfigration',
  'Resttaxmaster'   : 'HotelConfigration',
  'AccountingMasters': 'AccountingMasters',
  'AccountType'     : 'AccountingMasters',
  'AccountNature'   : 'AccountingMasters',
  'AccountLedger'   : 'AccountingMasters',
  'MenuMasters'     : 'MenuMasters',
  'ItemGroup'       : 'HotelConfigration',
  'ItemMainGroup'   : 'HotelConfigration',
  'KitchenCategories': 'HotelConfigration',
  'KitchenSubCategories': 'HotelConfigration',
  'KitchenGroup'    : 'HotelConfigration',
  'UnitMaster'      : 'HotelConfigration',
  'master-setting'  : 'master-setting',
  'master-role'     : 'master-setting',
  'master-zone'     : 'master-setting',
  'master-tax'      : 'master-setting',
  'master-package'  : 'master-setting',
  'Nationality-master': 'master-setting',
  'feature-master'  : 'master-setting',
  'fragment-master' : 'master-setting',
  'travel-agent-master': 'master-setting',
  'hotel-master'    : 'hotel-master',
  'floor-master'    : 'hotel-master',
  'block-master'    : 'hotel-master',
  'category-master' : 'hotel-master',
  'BillSetting'     : 'hotel-master',
  'InventoryMaster' : 'hotel-master',
  'room-master'     : 'hotel-master',
  'company-master'  : 'hotel-master',
  'Guest-master'    : 'hotel-master',
  'Complimentary-master': 'hotel-master',
  'HotelBookingPanel': 'hotel-master',
  'HotelReport'     : 'pages',

  'Settelement'     : 'hotel-master',

  'registration'    : 'registration',
  'registration-hotels-users': 'registration',

  // ❌ Apps section — map mein NAHI hain
  // POS, Settlement, Customers etc. map mein nahi = hide honge
}